import React from 'react';
import GridBlock from '@/components/grid/GridBlock';
import { SiBookstack } from "react-icons/si"; 
import { MdDataset, MdQuestionMark } from 'react-icons/md';
import { RiInstallFill } from 'react-icons/ri';

export default function Home() {
  return (
    <main className="px-8 lg:px-36">
      <section className="container p-4 mx-auto border-black border md:grid md:grid-cols-2 xl:grid-cols-3 gap-4">
        <GridBlock 
          icon={<SiBookstack size={30} className='fill-avaTeal'/>} 
          header="Background"
          subtext="Learn more about the algorithm, key concepts, and potential use cases."
          linkTo="/background"
        />
        <GridBlock 
          icon={<MdDataset size={35} className='fill-avaTeal'/>} 
          header="Data Examples"
          subtext="Data snippet examples generated by the avant algorithm."
          linkTo="/data-examples"
        />
        <GridBlock 
          icon={<RiInstallFill size={35} className='fill-avaTeal'/>} 
          header="Installation"
          subtext="Explore the different ways to get the algorithm up and running."
          linkTo="/installation"
        />
        <GridBlock 
          icon={<MdQuestionMark size={35} className='fill-avaTeal'/>} 
          header="How To Use"
          subtext="An extensive walkthrough highlighting general operation and the different modes found in avant."
          linkTo="/how-to-use"
        />
      </section>
    </main>
  );
}
